import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import ParticlesComponent from "@/components/ParticlesComponents";
const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-black/[0.96] antialiased bg-grid-white/[0.02] `}
      >
        <ParticlesComponent id="tsparticles" />
        {children}
      </body>
    </html>
  );
}
